<?xml version="1.0"?>
<package format="3">
  <name>svo_ceres_backend</name>
  <version>0.1.4</version>
  <description>
    svo_ceres_backend
  </description>
  <maintainer email="jhuber91@gmail.com">Jonathan Huber</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>svo_cmake</depend>
  <depend>svo_vio_common</depend>
  <depend>svo_common</depend>
  <depend>svo</depend>
  <depend>vikit_ros</depend>
  <depend>vikit_solver</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
