<?xml version="1.0"?>
<package format="3">
  <name>svo_pgo</name>
  <version>0.0.1</version>
  <description>The pose graph optimisation package</description>
  <author>Kunal Shrivastava</author>
  <maintainer email="kunalshrivastava.iitr@gmail.com">kunal71091</maintainer>

  <license>tbd</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>svo_cmake</depend>
  <depend>svo_common</depend>
  <depend>cv_bridge</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
